name: industrialdesign
favicon: null
layout_spectrum: 0.8703624515328556
typography_spectrum: 0.7585878313984722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3546180948615074
  lightness: 0.9037759692873806
  saturation: 0.9411557202693075
  rhythmicContrast: 0.12635739869438112
purpose: []
